[package]
name = "qs"
version = "0.1.0"
edition = "2021"

[dependencies]
selenium = { git = "https://github.com/inkroom/selenium-rs", version = "0.1.0" ,rev ="a5981933d15fa80053f941cd38213bddc2451b91" }
