name: calibre

on:
  push:
    paths:
      - '.github/workflows/calibre.yml'
      - 'calibre/Dockerfile'
    branches:
      - master
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: calibre
          push: false
          load: true
          file: calibre/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Export
        run: |
          image_id="${{ steps.build.outputs.imageid }}"
          image_id=${image_id:7}
          docker save -o image.tar $image_id
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar
      
