name: epub

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
   paths:
    - .github/epub.yml
    - 'epub/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: epub
          file: epub/Dockerfile
          tags: yn
          labels: yn
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: |
            type=local,dest=${{ github.workspace }}/epub.tar
      - name: Upload tar
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: |
            epub.tar