name: release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  rust:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout Runtime
        run: |
          git clone https://gist.github.com/inkroom/501548078a930c6f3bd98ea257409648 runtime
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.1
          override: true
      - name: Rust Latest Version
        id: v
        run: |
          cd rust
          cargo build --release
          ve=$(./target/release/rust)
          if [[ $ve == "null" ]]
          then 
            echo "暂无最新版本"
            echo "u=false" >> $GITHUB_OUTPUT
          fi
          d=$(docker run --rm ghcr.io/${{ github.repository_owner }}/rust:latest rustc --version || echo "null")
          echo "docker version=$d"
          echo "latest version=$ve"
          if [[ "$d" =~ "$ve"  ]]; then
            echo "已是最新版本"
            echo "u=false" >> $GITHUB_OUTPUT
          else 
            echo "最新版本 $ve"
            echo "u=true" >> $GITHUB_OUTPUT
            echo "ve=$ve" >> $GITHUB_OUTPUT
          fi
          tree
      - name: Set up QEMU
        if: steps.v.outputs.u == 'true'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: steps.v.outputs.u == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        if: steps.v.outputs.u == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Log in to the Docker Hub
        if: steps.v.outputs.u == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: steps.v.outputs.u == 'true'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/rust
            ${{ secrets.DOCKER_HUB_USERNAME }}/rust
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ steps.v.outputs.ve }}
          labels: |
            org.opencontainers.image.description=rust开发环境
            org.opencontainers.image.title=rust
      - name: Build Docker image
        uses: docker/build-push-action@v4
        if: steps.v.outputs.u == 'true'
        with:
          context: runtime
          file: runtime/Dockerfile.rust
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            RUST_VERSION=${{ steps.v.outputs.ve }}
