name: webide

on:
  workflow_dispatch:
    inputs:
      version: 
        description: version
        required: true
        type: string

jobs:
  webide:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout Runtime
        run: |
          git clone https://gist.github.com/inkroom/501548078a930c6f3bd98ea257409648 runtime
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/ide
            ${{ secrets.DOCKER_HUB_USERNAME }}/ide
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.description=webide, 带有node18、openjdk17
            org.opencontainers.image.title=webide
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: runtime
          file: runtime/Dockerfile.ide
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            IDE_VERSION=${{ inputs.version }}