name: yn

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ${{ github.workspace }}/image.tar
          key: yn-3
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          context: yn
          file: yn/Dockerfile.node
          push: false
          load: true
          tags: yn
          labels: yn
          build-args: |
            Y_USERNAME=${{ secrets.Y_USERNAME }}
            Y_PASSWORD=${{ secrets.Y_PASSWORD }}
      - name: Save Docker Image
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          docker save yn -o ${{ github.workspace }}/image.tar
      - name: Run Docker Image
        if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: |
          docker load -q -i ${{ github.workspace }}/image.tar
          docker run --rm -w /util/yn -e Y_USERNAME=${{ secrets.Y_USERNAME }} -e Y_PASSWORD=${{ secrets.Y_PASSWORD }} yn node yn.js
      - name: Retry the workflow
        if: github.event_name == 'schedule' && failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run yn.yml
