name: yn

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: yn
          file: yn/Dockerfile.yn
          push: false
          tags: yn
          labels: yn
          build-args: |
            Y_USERNAME=${{ secrets.Y_USERNAME }}
            Y_PASSWORD=${{ secrets.Y_PASSWORD }}
      - name: Retry the workflow
        if: github.event_name == 'schedule' && failure()
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/estruyf/doctor/actions/workflows/49809445/dispatches \
          -d '{"ref": "${{ github.ref }}" }'
