name: yn

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.yn
          push: false
          tags: yn
          labels: yn
          build-args: |
            Y_USERNAME=${{ secrets.Y_USERNAME }}
            Y_PASSWORD=${{ secrets.Y_PASSWORD }}
