name: yn

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Runtime
        run: |
          node i
          apt update -y && apt install -y firefox-esr
          mkdir /demo 
          cd /demo 
          wget https://kgithub.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux32.tar.gz
          tar -xvf geckodriver-v0.32.2-linux32.tar.gz

      - name: Run
        env:
          Y_USERNAME: ${{secrets.Y_USERNAME}}
          Y_PASSWORD: ${{secrets.Y_PASSWORD}}
        run: |
          node 1.js
